### ISSUE TITLE
WebServer startup Failed with Error: ws2811_init failed with code -3

### ISSUE THREAD

**Issue by AndreasBrunner** [adeept/Adeept_DarkPaw#3]
Hello,
 
yesterday night i finished assembling your darkpaw robot using a raspberry pi 4 8GB. I used your imagefile on a 256GB SD card. I've set up everything, but the WebServer wouldn't come up. After connecting via ssh to the robot and trying to startup the server by hand, i get the following messages:
 
sudo python3 webServer.py
mpu6050 connected
mpu6050 is connected and related functions are available.
loop
loop
Traceback (most recent call last):
  File "webServer.py", line 27, in <module>
    import app
  File "/home/pi/adeept_darkpaw/server/app.py", line 8, in <module>
    from camera_opencv import Camera
  File "/home/pi/adeept_darkpaw/server/camera_opencv.py", line 14, in <module>
    light = robotLight.RobotLight()
  File "/home/pi/adeept_darkpaw/server/robotLight.py", line 38, in __init__
    self.strip.begin()
  File "/usr/local/lib/python3.7/dist-packages/rpi_ws281x/rpi_ws281x.py", line 130, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
 
i tryied to update the firmware of the raspberry, which worked out, but the error stays the same :-( ... do you have any tips for me?
 
Kind Regards
 
    Andreas Brunner

**Comment by AndreasBrunner** [comment]
a simple:
sudo pip3 uninstall rpi_ws281x
and
sudo pip install rpi_ws281x
did the trick for me
